# Generated by Django 3.2.4 on 2021-06-07 22:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=25, verbose_name='Channel')),
                ('country', models.CharField(max_length=25, verbose_name='Channel')),
                ('os', models.CharField(max_length=25, verbose_name='Channel')),
                ('impressions', models.IntegerField(default=0, verbose_name='Impressions')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('installs', models.IntegerField(default=0, verbose_name='Installs')),
                ('spend', models.DecimalField(decimal_places=2, default=1.0, max_digits=15, verbose_name='Spend')),
                ('revenue', models.DecimalField(decimal_places=2, default=1.0, max_digits=15, verbose_name='Revenue')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
